europe: &europe
  currency:
    unit: €
    separator: ","
    delimiter: "."
    order:
    - number
    - unit
  date_select_order:
    order:
    - year
    - month
    - day
es: *europe
fr: *europe
de: *europe
it: *europe
uk:
  currency:
    unit: £
    separator: "."
    delimiter: ","
    order:
    - unit
    - number
  date_select_order:
    order:
    - year
    - month
    - day
us:
  currency:
    unit: $
    separator: "."
    delimiter: ","
    order:
    - unit
    - number
  date_select_order:
    order:
    - year
    - month
    - day
ca:
  currency:
    unit: $
    separator: "."
    delimiter: ","
    order:
    - unit
    - number
  date_select_order:
    order:
    - year
    - month
    - day