class Currency
  #TODO round should be an instance method, and there should be a factory
  
  def self.valid_currency?(currency_name)
    Currency.currency_hash.include?(currency_name) ? true : false
  end

  def self.currency_hash # http://en.wikipedia.org/wiki/List_of_circulating_currencies
  { 'AED' => { :currency => 'AED', :country => 'AE', :decimals => 2, :symbol => 'د.إ', :name => s_('AED|United Arab Emirates dirham'), :url => 'http://en.wikipedia.org/wiki/United_Arab_Emirates_dirham' },
    'AFN' => { :currency => 'AFN', :country => 'AF', :decimals => 2, :symbol => '؋', :name => s_('AFN|Afghan afghani'), :url => 'http://en.wikipedia.org/wiki/Afghan_afghani' },
    'ALL' => { :currency => 'ALL', :country => 'AL', :decimals => 2, :symbol => 'L', :name => s_('ALL|Albanian lek'), :url => 'http://en.wikipedia.org/wiki/Albanian_lek' },
    'AMD' => { :currency => 'AMD', :country => 'AM', :decimals => 2, :symbol => 'դր.', :name => s_('AMD|Armenian dram'), :url => 'http://en.wikipedia.org/wiki/Armenian_dram' },
    'ANG' => { :currency => 'ANG', :country => 'AN', :decimals => 2, :symbol => 'ƒ', :name => s_('ANG|Netherlands Antillean guilder'), :url => 'http://en.wikipedia.org/wiki/Netherlands_Antillean_guilder' },
    'AOA' => { :currency => 'AOA', :country => 'AO', :decimals => 2, :symbol => 'Kz', :name => s_('AOA|Angolan kwanza'), :url => 'http://en.wikipedia.org/wiki/Angolan_kwanza' },
    'ARS' => { :currency => 'ARS', :country => 'AR', :decimals => 2, :symbol => '$', :name => s_('ARS|Argentine peso'), :url => 'http://en.wikipedia.org/wiki/Argentine_peso' },
    'AUD' => { :currency => 'AUD', :country => 'AU', :decimals => 2, :symbol => 'A$', :name => s_('AUD|Australian dollar'), :url => 'http://en.wikipedia.org/wiki/Australian_dollar' },
    'AWG' => { :currency => 'AWG', :country => 'AW', :decimals => 2, :symbol => 'Afl.', :name => s_('AWG|Aruban florin'), :url => 'http://en.wikipedia.org/wiki/Aruban_florin' },
    'AZN' => { :currency => 'AZN', :country => 'AZ', :decimals => 2, :symbol => 'm', :name => s_('AZN|Azerbaijani manat'), :url => 'http://en.wikipedia.org/wiki/Azerbaijani_manat' },
    'BAM' => { :currency => 'BAM', :country => 'BA', :decimals => 2, :symbol => 'KM', :name => s_('BAM|Bosnia and Herzegovina convertible mark'), :url => 'http://en.wikipedia.org/wiki/Bosnia_and_Herzegovina_convertible_mark' },
    'BBD' => { :currency => 'BBD', :country => 'BB', :decimals => 2, :symbol => '$', :name => s_('BBD|Barbadian dollar'), :url => 'http://en.wikipedia.org/wiki/Barbadian_dollar' },
    'BDT' => { :currency => 'BDT', :country => 'BD', :decimals => 2, :symbol => '৳', :name => s_('BDT|Bangladeshi taka'), :url => 'http://en.wikipedia.org/wiki/Bangladeshi_taka' },
    'BGN' => { :currency => 'BGN', :country => 'BG', :decimals => 2, :symbol => 'лв', :name => s_('BGN|Bulgarian lev'), :url => 'http://en.wikipedia.org/wiki/Bulgarian_lev' }, # Euro 2015 (?)
    'BHD' => { :currency => 'BHD', :country => 'BH', :decimals => 3, :symbol => 'ب.د', :name => s_('BHD|Bahraini dinar'), :url => 'http://en.wikipedia.org/wiki/Bahraini_dinar' },
    'BIF' => { :currency => 'BIF', :country => 'BI', :decimals => 2, :symbol => 'Fr', :name => s_('BIF|Burundian franc'), :url => 'http://en.wikipedia.org/wiki/Burundian_franc' },
    'BMD' => { :currency => 'BMD', :country => 'BM', :decimals => 2, :symbol => 'BD$', :name => s_('BMD|Bermudian dollar'), :url => 'http://en.wikipedia.org/wiki/Bermudian_dollar' },
    'BND' => { :currency => 'BND', :country => 'BN', :decimals => 2, :symbol => 'B$', :name => s_('BND|Brunei dollar'), :url => 'http://en.wikipedia.org/wiki/Brunei_dollar' },
    'BOB' => { :currency => 'BOB', :country => 'BO', :decimals => 2, :symbol => 'Bs.', :name => s_('BOB|Bolivian boliviano'), :url => 'http://en.wikipedia.org/wiki/Bolivian_boliviano' },
    'BRL' => { :currency => 'BRL', :country => 'BR', :decimals => 2, :symbol => 'R$', :name => s_('BRL|Brazilian real'), :url => 'http://en.wikipedia.org/wiki/Brazilian_real' },
    'BSD' => { :currency => 'BSD', :country => 'BS', :decimals => 2, :symbol => '$', :name => s_('BSD|Bahamian dollar'), :url => 'http://en.wikipedia.org/wiki/Bahamian_dollar' },
    'BTN' => { :currency => 'BTN', :country => 'BT', :decimals => 2, :symbol => 'Nu.', :name => s_('BTN|Bhutanese ngultrum'), :url => 'http://en.wikipedia.org/wiki/Bhutanese_ngultrum' },
    'BWP' => { :currency => 'BWP', :country => 'BW', :decimals => 2, :symbol => 'P', :name => s_('BWP|Botswana pula'), :url => 'http://en.wikipedia.org/wiki/Botswana_pula' },
    'BYR' => { :currency => 'BYR', :country => 'BY', :decimals => 2, :symbol => 'Br', :name => s_('BYR|Belarusian ruble'), :url => 'http://en.wikipedia.org/wiki/Belarusian_ruble' },
    'BZD' => { :currency => 'BZD', :country => 'BZ', :decimals => 2, :symbol => 'BZ$', :name => s_('BZD|Belize dollar'), :url => 'http://en.wikipedia.org/wiki/Belize_dollar' },
    'CAD' => { :currency => 'CAD', :country => 'CA', :decimals => 2, :symbol => 'Can$', :name => s_('CAD|Canadian dollar'), :url => 'http://en.wikipedia.org/wiki/Canadian_dollar' },
    'CDF' => { :currency => 'CDF', :country => 'CD', :decimals => 2, :symbol => 'Fr', :name => s_('CDF|Congolese franc'), :url => 'http://en.wikipedia.org/wiki/Congolese_franc' },
    'CHF' => { :currency => 'CHF', :country => 'CH', :decimals => 2, :symbol => 'SwF', :name => s_('CHF|Swiss franc'), :url => 'http://en.wikipedia.org/wiki/Swiss_franc' },
    'CLP' => { :currency => 'CLP', :country => 'CL', :decimals => 2, :symbol => '$', :name => s_('CLP|Chilean peso'), :url => 'http://en.wikipedia.org/wiki/Chilean_peso' },
    'CNY' => { :currency => 'CNY', :country => 'CN', :decimals => 2, :symbol => '元', :name => s_('CNY|Chinese renminbi'), :url => 'http://en.wikipedia.org/wiki/Renminbi' },
    'COP' => { :currency => 'COP', :country => 'CO', :decimals => 2, :symbol => '$', :name => s_('COP|Colombian peso'), :url => 'http://en.wikipedia.org/wiki/Colombian_peso' },
    'CRC' => { :currency => 'CRC', :country => 'CR', :decimals => 2, :symbol => '&#8353;', :name => s_('CRC|Costa Rican colón'), :url => 'http://en.wikipedia.org/wiki/Costa_Rican_col%C3%B3n' },
    'CUC' => { :currency => 'CUC', :country => 'CU', :decimals => 2, :symbol => 'CUC$', :name => s_('CUC|Cuban convertible peso'), :url => 'http://en.wikipedia.org/wiki/Cuban_convertible_peso' },
    'CUP' => { :currency => 'CUP', :country => 'CU', :decimals => 2, :symbol => '$MN', :name => s_('CUP|Cuban peso'), :url => 'http://en.wikipedia.org/wiki/Cuban_peso' },
    'CVE' => { :currency => 'CVE', :country => 'CV', :decimals => 2, :symbol => 'Esc', :name => s_('CVE|Cape Verdean escudo'), :url => 'http://en.wikipedia.org/wiki/Cape_Verdean_escudo' },
    'CZK' => { :currency => 'CZK', :country => 'CZ', :decimals => 2, :symbol => 'Kč', :name => s_('CZK|Czech koruna'), :url => 'http://en.wikipedia.org/wiki/Czech_koruna' }, # Euro 2019
    'DJF' => { :currency => 'DJF', :country => 'DJ', :decimals => 2, :symbol => 'Fdj', :name => s_('DJF|Djiboutian franc'), :url => 'http://en.wikipedia.org/wiki/Djiboutian_franc' },
    'DKK' => { :currency => 'DKK', :country => 'DK', :decimals => 2, :symbol => 'Dkr', :name => s_('DKK|Danish krone'), :url => 'http://en.wikipedia.org/wiki/Danish_krone' }, # Euro vote forthcoming
    'DOP' => { :currency => 'DOP', :country => 'DO', :decimals => 2, :symbol => 'RD$', :name => s_('DOP|Dominican peso'), :url => 'http://en.wikipedia.org/wiki/Dominican_peso' },
    'DZD' => { :currency => 'DZD', :country => 'DZ', :decimals => 2, :symbol => 'د.ج', :name => s_('DZD|Algerian dinar'), :url => 'http://en.wikipedia.org/wiki/Algerian_dinar' },
    'EEK' => { :currency => 'EEK', :country => 'EE', :decimals => 2, :symbol => 'KR', :name => s_('EEK|Estonian kroon'), :url => 'http://en.wikipedia.org/wiki/Estonian_kroon' }, # Euro 2011
    'EGP' => { :currency => 'EGP', :country => 'EG', :decimals => 2, :symbol => 'ج.م', :name => s_('EGP|Egyptian pound'), :url => 'http://en.wikipedia.org/wiki/Egyptian_pound' },
    'ERN' => { :currency => 'ERN', :country => 'ER', :decimals => 2, :symbol => 'Nfk', :name => s_('ERN|Eritrean nakfa'), :url => 'http://en.wikipedia.org/wiki/Eritrean_nakfa' },
    'ETB' => { :currency => 'ETB', :country => 'ET', :decimals => 2, :symbol => 'Br', :name => s_('ETB|Ethiopian birr'), :url => 'http://en.wikipedia.org/wiki/Ethiopian_birr' },
    'EUR' => { :currency => 'EUR', :country => 'EU', :decimals => 2, :symbol => '&#8364;', :name => s_('EUR|Euro'), :url => 'http://en.wikipedia.org/wiki/Euro' },
    'FJD' => { :currency => 'FJD', :country => 'FJ', :decimals => 2, :symbol => 'F$', :name => s_('FJD|Fijian dollar'), :url => 'http://en.wikipedia.org/wiki/Fijian_dollar' },
    'FKP' => { :currency => 'FKP', :country => 'FK', :decimals => 2, :symbol => '£', :name => s_('FKP|Falkland Islands pound'), :url => 'http://en.wikipedia.org/wiki/Falkland_Islands_pound' },
    'GBP' => { :currency => 'GBP', :country => 'GB', :decimals => 2, :symbol => '&#163;', :name => s_('GBP|UK pound sterling'), :url => 'http://en.wikipedia.org/wiki/Pound_sterling' },
    'GEL' => { :currency => 'GEL', :country => 'GE', :decimals => 2, :symbol => 'ლ', :name => s_('GEL|Georgian lari'), :url => 'http://en.wikipedia.org/wiki/Georgian_lari' },
    'GHS' => { :currency => 'GHS', :country => 'GH', :decimals => 2, :symbol => '₵', :name => s_('GHS|Ghanaian cedi'), :url => 'http://en.wikipedia.org/wiki/Ghanaian_cedi' },
    'GIP' => { :currency => 'GIP', :country => 'GI', :decimals => 2, :symbol => '£G', :name => s_('GIP|Gibraltar pound'), :url => 'http://en.wikipedia.org/wiki/Gibraltar_pound' },
    'GMB' => { :currency => 'GMB', :country => 'GM', :decimals => 2, :symbol => 'D', :name => s_('GMB|Gambian dalasi'), :url => 'http://en.wikipedia.org/wiki/Gambian_dalasi' },
    'GNF' => { :currency => 'GNF', :country => 'GN', :decimals => 2, :symbol => 'Fr', :name => s_('GNF|Guinean franc'), :url => 'http://en.wikipedia.org/wiki/Guinean_franc' },
    'GTQ' => { :currency => 'GTQ', :country => 'GT', :decimals => 2, :symbol => 'Q', :name => s_('GTQ|Guatemalan quetzal'), :url => 'http://en.wikipedia.org/wiki/Guatemalan_quetzal' },
    'GYD' => { :currency => 'GYD', :country => 'GY', :decimals => 2, :symbol => '$', :name => s_('GYD|Guyanese dollar'), :url => 'http://en.wikipedia.org/wiki/Guyanese_dollar' },
    'HKD' => { :currency => 'HKD', :country => 'HK', :decimals => 2, :symbol => 'HK$', :name => s_('HKD|Hong Kong dollar'), :url => 'http://en.wikipedia.org/wiki/Hong_Kong_Dollar' },
    'HNL' => { :currency => 'HNL', :country => 'HN', :decimals => 2, :symbol => 'L', :name => s_('HNL|Honduran lempira'), :url => 'http://en.wikipedia.org/wiki/Honduran_lempira' },
    'HRK' => { :currency => 'HRK', :country => 'HR', :decimals => 2, :symbol => 'kn', :name => s_('HRK|Croatian kuna'), :url => 'http://en.wikipedia.org/wiki/Croatian_kuna' },
    'HTG' => { :currency => 'HTG', :country => 'HT', :decimals => 2, :symbol => 'G', :name => s_('HTG|Haitian gourde'), :url => 'http://en.wikipedia.org/wiki/Haitian_gourde' },
    'HUF' => { :currency => 'HUF', :country => 'HU', :decimals => 2, :symbol => 'Ft', :name => s_('HUF|Hungarian forint'), :url => 'http://en.wikipedia.org/wiki/Hungarian_forint' }, # Euro 2013
    'IDR' => { :currency => 'IDR', :country => 'ID', :decimals => 2, :symbol => 'Rp.', :name => s_('IDR|Indonesian rupiah'), :url => 'http://en.wikipedia.org/wiki/Indonesian_rupiah' },
    'ILS' => { :currency => 'ILS', :country => 'IL', :decimals => 2, :symbol => '₪', :name => s_('ILS|New Israeli Sheqel'), :url => 'http://en.wikipedia.org/wiki/New_Israeli_Sheqel' },
    'INR' => { :currency => 'INR', :country => 'IN', :decimals => 2, :symbol => 'Rs', :name => s_('INR|Indian rupee'), :url => 'http://en.wikipedia.org/wiki/Indian_rupee' },
    'IQD' => { :currency => 'IQD', :country => 'IQ', :decimals => 3, :symbol => 'ع.د', :name => s_('IQD|Iraqi dinar'), :url => 'http://en.wikipedia.org/wiki/Iraqi_dinar' },
    'IRR' => { :currency => 'IRR', :country => 'IR', :decimals => 2, :symbol => '﷼', :name => s_('IRR|Iranian rial'), :url => 'http://en.wikipedia.org/wiki/Iranian_rial' },
    'ISK' => { :currency => 'ISK', :country => 'IS', :decimals => 2, :symbol => 'IKr', :name => s_('ISK|Icelandic króna'), :url => 'http://en.wikipedia.org/wiki/Icelandic_kr%C3%B3na' },
    'JMD' => { :currency => 'JMD', :country => 'JM', :decimals => 2, :symbol => '$', :name => s_('JMD|Jamaican dollar'), :url => 'http://en.wikipedia.org/wiki/Jamaican_dollar' },
    'JOD' => { :currency => 'JOD', :country => 'JO', :decimals => 2, :symbol => 'د.ا', :name => s_('JOD|Jordanian dinar'), :url => 'http://en.wikipedia.org/wiki/Jordanian_dinar' },
    'JPY' => { :currency => 'JPY', :country => 'JP', :decimals => 2, :symbol => '¥', :name => s_('JPY|Japanese yen'), :url => 'http://en.wikipedia.org/wiki/Japanese_yen' },
    'KES' => { :currency => 'KES', :country => 'KE', :decimals => 2, :symbol => 'Sh', :name => s_('KES|Kenyan shilling'), :url => 'http://en.wikipedia.org/wiki/Kenyan_shilling' },
    'KGS' => { :currency => 'KGS', :country => 'KG', :decimals => 2, :symbol => '', :name => s_('KGS|Kyrgyzstani som'), :url => 'http://en.wikipedia.org/wiki/Kyrgyzstani_som' },
    'KHR' => { :currency => 'KHR', :country => 'KH', :decimals => 2, :symbol => '៛', :name => s_('KHR|Cambodian riel'), :url => 'http://en.wikipedia.org/wiki/Cambodian_riel' },
    'KMF' => { :currency => 'KMF', :country => 'KM', :decimals => 2, :symbol => 'CF', :name => s_('KMF|Comorian franc'), :url => 'http://en.wikipedia.org/wiki/Comorian_franc' },
    'KPW' => { :currency => 'KPW', :country => 'KP', :decimals => 2, :symbol => '₩', :name => s_('KPW|North Korean won'), :url => 'http://en.wikipedia.org/wiki/North_Korean_won' },
    'KRW' => { :currency => 'KRW', :country => 'KR', :decimals => 2, :symbol => '₩', :name => s_('KRW|South Korean won'), :url => 'http://en.wikipedia.org/wiki/South_Korean_won' },
    'KWD' => { :currency => 'KWD', :country => 'KW', :decimals => 3, :symbol => 'د.ك', :name => s_('KWD|Kuwaiti dinar'), :url => 'http://en.wikipedia.org/wiki/Kuwaiti_dinar' },
    'KYD' => { :currency => 'KYD', :country => 'KY', :decimals => 2, :symbol => '$', :name => s_('KYD|Cayman Islands dollar'), :url => 'http://en.wikipedia.org/wiki/Cayman_Islands_dollar' },
    'KZT' => { :currency => 'KZT', :country => 'KZ', :decimals => 2, :symbol => '〒', :name => s_('KZT|Kazakhstani tenge'), :url => 'http://en.wikipedia.org/wiki/Kazakhstani_tenge' },
    'LAK' => { :currency => 'LAK', :country => 'LA', :decimals => 2, :symbol => 'Kip', :name => s_('LAK|Lao kip'), :url => 'http://en.wikipedia.org/wiki/Lao_kip' },
    'LBP' => { :currency => 'LBP', :country => 'LB', :decimals => 2, :symbol => 'ل.ل', :name => s_('LBP|Lebanese pound'), :url => 'http://en.wikipedia.org/wiki/Lebanese_pound' },
    'LKR' => { :currency => 'LKR', :country => 'LK', :decimals => 2, :symbol => '₨', :name => s_('LKR|Sri Lankan rupee'), :url => 'http://en.wikipedia.org/wiki/Sri_Lankan_rupee' },
    'LRD' => { :currency => 'LRD', :country => 'LR', :decimals => 2, :symbol => 'L$', :name => s_('LRD|Liberian dollar'), :url => 'http://en.wikipedia.org/wiki/Liberian_dollar' },
    'LSL' => { :currency => 'LSL', :country => 'LS', :decimals => 2, :symbol => 'L', :name => s_('LSL|Lesotho loti'), :url => 'http://en.wikipedia.org/wiki/Lesotho_loti' },
    'LTL' => { :currency => 'LTL', :country => 'LT', :decimals => 2, :symbol => 'Lt', :name => s_('LTL|Lithuanian litas'), :url => 'http://en.wikipedia.org/wiki/Lithuanian_litas' },
    'LVL' => { :currency => 'LVL', :country => 'LV', :decimals => 2, :symbol => 'Ls', :name => s_('LVL|Latvian lats'), :url => 'http://en.wikipedia.org/wiki/Latvian_lats' }, # Euro 2012
    'LYD' => { :currency => 'LYD', :country => 'LY', :decimals => 2, :symbol => 'ل.د', :name => s_('LYD|Libyan dinar'), :url => 'http://en.wikipedia.org/wiki/Libyan_dinar' },
    'MAD' => { :currency => 'MAD', :country => 'MA', :decimals => 2, :symbol => 'د.م.', :name => s_('MAD|Moroccan dirham'), :url => 'http://en.wikipedia.org/wiki/Moroccan_dirham' },
    'MDL' => { :currency => 'MDL', :country => 'MD', :decimals => 2, :symbol => 'L', :name => s_('MDL|Moldovan leu'), :url => 'http://en.wikipedia.org/wiki/Moldovan_leu' },
    'MGA' => { :currency => 'MGA', :country => 'MG', :decimals => 2, :symbol => '', :name => s_('MGA|Malagasy ariary'), :url => 'http://en.wikipedia.org/wiki/Malagasy_ariary' },
    'MKD' => { :currency => 'MKD', :country => 'MK', :decimals => 2, :symbol => 'ден', :name => s_('MKD|Macedonian denar'), :url => 'http://en.wikipedia.org/wiki/Macedonian_denar' },
    'MMK' => { :currency => 'MMK', :country => 'MM', :decimals => 2, :symbol => 'K', :name => s_('MMK|Myanma kyat'), :url => 'http://en.wikipedia.org/wiki/Myanma_kyat' },
    'MNT' => { :currency => 'MNT', :country => 'MN', :decimals => 2, :symbol => '₮', :name => s_('MNT|Mongolian tögrög'), :url => 'http://en.wikipedia.org/wiki/Mongolian_t%C3%B6gr%C3%B6g' },
    'MOP' => { :currency => 'MOP', :country => 'MO', :decimals => 2, :symbol => 'P', :name => s_('MOP|Macanese pataca'), :url => 'http://en.wikipedia.org/wiki/Macanese_pataca' },
    'MRO' => { :currency => 'MRO', :country => 'MR', :decimals => 2, :symbol => 'UM', :name => s_('MRO|Mauritanian ouguiya'), :url => 'http://en.wikipedia.org/wiki/Mauritanian_ouguiya' },
    'MUR' => { :currency => 'MUR', :country => 'MU', :decimals => 2, :symbol => '₨', :name => s_('MUR|Mauritian rupee'), :url => 'http://en.wikipedia.org/wiki/Mauritian_rupee' },
    'MVR' => { :currency => 'MVR', :country => 'MV', :decimals => 2, :symbol => 'ރ.', :name => s_('MVR|Maldivian rufiyaa'), :url => 'http://en.wikipedia.org/wiki/Maldivian rufiyaa' },
    'MWK' => { :currency => 'MWK', :country => 'MW', :decimals => 2, :symbol => 'MK', :name => s_('MWK|Malawian kwacha'), :url => 'http://en.wikipedia.org/wiki/Malawian_kwacha' },
    'MXN' => { :currency => 'MXN', :country => 'MX', :decimals => 2, :symbol => 'Mex$', :name => s_('MXN|Mexican peso'), :url => 'http://en.wikipedia.org/wiki/Mexican_peso' },
    'MYR' => { :currency => 'MYR', :country => 'MY', :decimals => 2, :symbol => 'RM', :name => s_('MYR|Malaysian ringgit'), :url => 'http://en.wikipedia.org/wiki/Malaysian_ringgit' },
    'MZN' => { :currency => 'MZN', :country => 'MZ', :decimals => 2, :symbol => 'MTn', :name => s_('MZN|Mozambican metical'), :url => 'http://en.wikipedia.org/wiki/Mozambican_metical' },
    'NAD' => { :currency => 'NAD', :country => 'NA', :decimals => 2, :symbol => '$', :name => s_('NAD|Namibian dollar'), :url => 'http://en.wikipedia.org/wiki/Namibian_dollar' },
    'NGN' => { :currency => 'NGN', :country => 'NG', :decimals => 2, :symbol => '₦', :name => s_('NGN|Nigerian naira'), :url => 'http://en.wikipedia.org/wiki/Nigerian_naira' },
    'NIO' => { :currency => 'NIO', :country => 'NI', :decimals => 2, :symbol => 'C$', :name => s_('NIO|Nicaraguan córdoba'), :url => 'http://en.wikipedia.org/wiki/Nicaraguan_córdoba' },
    'NOK' => { :currency => 'NOK', :country => 'NO', :decimals => 2, :symbol => 'Nkr', :name => s_('NOK|Norwegian krone'), :url => 'http://en.wikipedia.org/wiki/Norwegian_krone' },
    'NPR' => { :currency => 'NPR', :country => 'NP', :decimals => 2, :symbol => '₨', :name => s_('NPR|Nepalese rupee'), :url => 'http://en.wikipedia.org/wiki/Nepalese_rupee' },
    'NZD' => { :currency => 'NZD', :country => 'NZ', :decimals => 2, :symbol => 'NZ$', :name => s_('NZD|New Zealand dollar'), :url => 'http://en.wikipedia.org/wiki/New_Zealand_dollar' },
    'OMR' => { :currency => 'OMR', :country => 'OM', :decimals => 3, :symbol => 'ر.ع.', :name => s_('OMR|Omani rial'), :url => 'http://en.wikipedia.org/wiki/Omani_rial' },
    'PAB' => { :currency => 'PAB', :country => 'PA', :decimals => 2, :symbol => 'B/.', :name => s_('PAB|Panamanian balboa'), :url => 'http://en.wikipedia.org/wiki/Panamanian_balboa' },
    'PEN' => { :currency => 'PEN', :country => 'PE', :decimals => 2, :symbol => 'S/.', :name => s_('PEN|Peruvian nuevo sol'), :url => 'http://en.wikipedia.org/wiki/Peruvian_nuevo_sol' },
    'PGK' => { :currency => 'PGK', :country => 'PG', :decimals => 2, :symbol => 'K', :name => s_('PGK|Papua New Guinean kina'), :url => 'http://en.wikipedia.org/wiki/Papua_New_Guinean_kina' },
    'PHP' => { :currency => 'PHP', :country => 'PH', :decimals => 2, :symbol => '₱', :name => s_('PHP|Philippine peso'), :url => 'http://en.wikipedia.org/wiki/Philippine_peso' },
    'PKR' => { :currency => 'PKR', :country => 'PK', :decimals => 2, :symbol => '₨', :name => s_('PKR|Pakistani rupee'), :url => 'http://en.wikipedia.org/wiki/Pakistani_rupee' },
    'PLN' => { :currency => 'PLN', :country => 'PL', :decimals => 2, :symbol => 'zł', :name => s_('PLN|Polish złoty'), :url => 'http://en.wikipedia.org/wiki/Polish_z%C5%82oty' }, # Euro 2012
    'PYG' => { :currency => 'PYG', :country => 'PY', :decimals => 2, :symbol => '₲', :name => s_('PYG|Paraguayan guaraní'), :url => 'http://en.wikipedia.org/wiki/Paraguayan_guaraní' },
    'QAR' => { :currency => 'QAR', :country => 'QA', :decimals => 2, :symbol => 'ر.ق', :name => s_('QAR|Qatari riyal'), :url => 'http://en.wikipedia.org/wiki/Qatari_riyal' },
    'RON' => { :currency => 'RON', :country => 'RO', :decimals => 2, :symbol => 'L', :name => s_('RON|Romanian leu'), :url => 'http://en.wikipedia.org/wiki/Romanian_leu' }, #Euro 2014
    'RSD' => { :currency => 'RSD', :country => 'RS', :decimals => 2, :symbol => 'дин.', :name => s_('RSD|Serbian dinar'), :url => 'http://en.wikipedia.org/wiki/Serbian_dinar' },
    'RUB' => { :currency => 'RUB', :country => 'RU', :decimals => 2, :symbol => 'руб', :name => s_('RUB|Russian ruble'), :url => 'http://en.wikipedia.org/wiki/Russian_ruble' },
    'RWF' => { :currency => 'RWF', :country => 'RW', :decimals => 2, :symbol => 'Fr', :name => s_('RWF|Rwandan franc'), :url => 'http://en.wikipedia.org/wiki/Rwandan_franc' },
    'SAR' => { :currency => 'SAR', :country => 'SA', :decimals => 2, :symbol => 'ر.س', :name => s_('SAR|Saudi riyal'), :url => 'http://en.wikipedia.org/wiki/Saudi_riyal' },
    'SBD' => { :currency => 'SBD', :country => 'SB', :decimals => 2, :symbol => '$', :name => s_('SBD|Solomon Islands dollar'), :url => 'http://en.wikipedia.org/wiki/Solomon_Islands_dollar' },
    'SCR' => { :currency => 'SCR', :country => 'SC', :decimals => 2, :symbol => '₨', :name => s_('SCR|Seychellois rupee'), :url => 'http://en.wikipedia.org/wiki/Seychellois_rupee' },
    'SDG' => { :currency => 'SDG', :country => 'SD', :decimals => 2, :symbol => '£', :name => s_('SDG|Sudanese pound'), :url => 'http://en.wikipedia.org/wiki/Sudanese_pound' },
    'SEK' => { :currency => 'SEK', :country => 'SE', :decimals => 2, :symbol => 'Skr', :name => s_('SEK|Swedish krona'), :url => 'http://en.wikipedia.org/wiki/Swedish_krona' },
    'SGD' => { :currency => 'SGD', :country => 'SG', :decimals => 2, :symbol => 'S$', :name => s_('SGD|Singapore dollar'), :url => 'http://en.wikipedia.org/wiki/Singapore_dollar' },
    'SHP' => { :currency => 'SHP', :country => 'SH', :decimals => 2, :symbol => '£', :name => s_('SHP|Saint Helena pound'), :url => 'http://en.wikipedia.org/wiki/Saint_Helena_pound' },
    'SLL' => { :currency => 'SLL', :country => 'SL', :decimals => 2, :symbol => 'Le', :name => s_('SLL|Sierra Leonean leone'), :url => 'http://en.wikipedia.org/wiki/Sierra_Leonean_leone' },
    'SOS' => { :currency => 'SOS', :country => 'SO', :decimals => 2, :symbol => 'Sh', :name => s_('SOS|Somali shilling'), :url => 'http://en.wikipedia.org/wiki/Somali_shilling' },
    'SRD' => { :currency => 'SRD', :country => 'SR', :decimals => 2, :symbol => '$', :name => s_('SRD|Surinamese dollar'), :url => 'http://en.wikipedia.org/wiki/Surinamese_dollar' },
    'STD' => { :currency => 'STD', :country => 'ST', :decimals => 2, :symbol => 'Db', :name => s_('STD|São Tomé and Príncipe dobra'), :url => 'http://en.wikipedia.org/wiki/São_Tomé_and_Príncipe_dobra' },
    'SYP' => { :currency => 'SYP', :country => 'SY', :decimals => 2, :symbol => 'ل.س', :name => s_('SYP|Syrian pound'), :url => 'http://en.wikipedia.org/wiki/Syrian_pound' },
    'SZL' => { :currency => 'SZL', :country => 'SZ', :decimals => 2, :symbol => 'L', :name => s_('SZL|Swazi lilangeni'), :url => 'http://en.wikipedia.org/wiki/Swazi_lilangeni' },
    'THB' => { :currency => 'THB', :country => 'TH', :decimals => 2, :symbol => '฿', :name => s_('THB|Thai baht'), :url => 'http://en.wikipedia.org/wiki/Thai_baht' },
    'TJS' => { :currency => 'TJS', :country => 'TJ', :decimals => 2, :symbol => 'ЅМ', :name => s_('TJS|Tajikistani somoni'), :url => 'http://en.wikipedia.org/wiki/Tajikistani_somoni' },
    'TMM' => { :currency => 'TMM', :country => 'TM', :decimals => 2, :symbol => 'm', :name => s_('TMM|Turkmenistani manat'), :url => 'http://en.wikipedia.org/wiki/Turkmenistani_manat' },
    'TND' => { :currency => 'TND', :country => 'TN', :decimals => 2, :symbol => 'د.ت', :name => s_('TND|Tunisian dinar'), :url => 'http://en.wikipedia.org/wiki/Tunisian_dinar' },
    'TOP' => { :currency => 'TOP', :country => 'TO', :decimals => 2, :symbol => 'T$', :name => s_('TOP|Tongan paʻanga'), :url => 'http://en.wikipedia.org/wiki/Tongan_pa%CA%BBanga' },
    'TRY' => { :currency => 'TRY', :country => 'TR', :decimals => 2, :symbol => 'YTL', :name => s_('TRY|New Turkish Lira'), :url => 'http://en.wikipedia.org/wiki/New_Turkish_Lira' },
    'TTD' => { :currency => 'TTD', :country => 'TT', :decimals => 2, :symbol => '$', :name => s_('TTD|Trinidad and Tobago dollar'), :url => 'http://en.wikipedia.org/wiki/Trinidad_and_Tobago_dollar' },
    'TWD' => { :currency => 'TWD', :country => 'TW', :decimals => 2, :symbol => 'NT$', :name => s_('TWD|New Taiwan dollar'), :url => 'http://en.wikipedia.org/wiki/New_Taiwan_dollar' },
    'TZS' => { :currency => 'TZS', :country => 'TZ', :decimals => 2, :symbol => 'Sh', :name => s_('TZS|Tanzanian shilling'), :url => 'http://en.wikipedia.org/wiki/Tanzanian_shilling' },
    'UAH' => { :currency => 'UAH', :country => 'UA', :decimals => 2, :symbol => '₴', :name => s_('UAH|Ukrainian hryvnia'), :url => 'http://en.wikipedia.org/wiki/Ukrainian_hryvnia' },
    'UGX' => { :currency => 'UGX', :country => 'UG', :decimals => 2, :symbol => 'Sh', :name => s_('UGX|Ugandan shilling'), :url => 'http://en.wikipedia.org/wiki/Ugandan_shilling' },
    'USD' => { :currency => 'USD', :country => 'US', :decimals => 2, :symbol => '$', :name => s_('USD|United States dollar'), :url => 'http://en.wikipedia.org/wiki/United_States_dollar' },
    'UYU' => { :currency => 'UYU', :country => 'UY', :decimals => 2, :symbol => '$', :name => s_('UYU|Uruguayan peso'), :url => 'http://en.wikipedia.org/wiki/Uruguayan_peso' },
    'UZS' => { :currency => 'UZS', :country => 'UZ', :decimals => 2, :symbol => '$', :name => s_('UZS|Uzbekistani som'), :url => 'http://en.wikipedia.org/wiki/Uzbekistani_som' },
    'VEF' => { :currency => 'VEF', :country => 'VE', :decimals => 2, :symbol => 'Bs F', :name => s_('VEF|Venezuelan bolívar'), :url => 'http://en.wikipedia.org/wiki/Venezuelan_bolívar' },
    'VND' => { :currency => 'VND', :country => 'VN', :decimals => 1, :symbol => '₫', :name => s_('VND|Vietnamese đồng'), :url => 'http://en.wikipedia.org/wiki/Vietnamese_%C4%91%E1%BB%93ng' },
    'VUV' => { :currency => 'VUV', :country => 'VU', :decimals => 0, :symbol => 'Vt', :name => s_('VUV|Vanuatu vatu'), :url => 'http://en.wikipedia.org/wiki/Vanuatu_vatu' },
    'WST' => { :currency => 'WST', :country => 'WS', :decimals => 2, :symbol => 'T', :name => s_('WST|Samoan tala'), :url => 'http://en.wikipedia.org/wiki/Samoan_tala' },
    'XAF' => { :currency => 'XAF', :country => '',   :decimals => 2, :symbol => 'Fr', :name => s_('XAF|Central African CFA franc'), :url => 'http://en.wikipedia.org/wiki/C_African_CFA_franc' },
    'XCD' => { :currency => 'XCD', :country => '',   :decimals => 2, :symbol => '$', :name => s_('XCD|East Caribbean dollar'), :url => 'http://en.wikipedia.org/wiki/East_Caribbean_dollar' },
    'XOF' => { :currency => 'XOF', :country => '',   :decimals => 2, :symbol => 'Fr', :name => s_('XOF|West African CFA franc'), :url => 'http://en.wikipedia.org/wiki/West_African_CFA_franc' },
    'XPF' => { :currency => 'XPF', :country => '',   :decimals => 2, :symbol => 'Fr', :name => s_('XPF|CFP franc'), :url => 'http://en.wikipedia.org/wiki/CFP_franc' },
    'YER' => { :currency => 'YER', :country => 'YE', :decimals => 2, :symbol => '﷼', :name => s_('YER|Yemeni rial'), :url => 'http://en.wikipedia.org/wiki/Yemeni_rial' },
    'ZAR' => { :currency => 'ZAR', :country => 'ZA', :decimals => 2, :symbol => 'R', :name => s_('ZAR|South African rand'), :url => 'http://en.wikipedia.org/wiki/South_African_rand' },
    'ZMK' => { :currency => 'ZMK', :country => 'ZM', :decimals => 2, :symbol => 'ZK', :name => s_('ZMK|Zambian kwacha'), :url => 'http://en.wikipedia.org/wiki/Zambian_kwacha' },
    'ZWD' => { :currency => 'ZWD', :country => 'ZW', :decimals => 2, :symbol => 'Z$', :name => s_('ZWD|Zimbabwean dollar'), :url => 'http://en.wikipedia.org/wiki/Zimbabwean_dollar' }}
  end
  
  def self.currencies_for_countries
    { 'AD' => 'EUR',
      'AE' => 'AED',
      'AF' => 'AFN',
      'AG' => 'XCD',
      'AI' => 'XCD',
      'AL' => 'ALL',
      'AM' => 'AMD',
      'AN' => 'ANG',
      'AO' => 'AOA',
      'AR' => 'ARS',
      'AS' => 'USD',
      'AT' => 'EUR',
      'AU' => 'AUD',
      'AW' => 'AWG',
      'AZ' => 'AZN',
      'BA' => 'BAM',
      'BB' => 'BBD',
      'BD' => 'BDT',
      'BE' => 'EUR',
      'BF' => 'XOF',
      'BG' => 'BGN',
      'BH' => 'BHD',
      'BI' => 'BIF',
      'BJ' => 'XOF',
      'BM' => 'BMD',
      'BN' => 'BND',
      'BO' => 'BOB',
      'BR' => 'BRL',
      'BS' => 'BSD',
      'BT' => 'BTN',
      'BW' => 'BWP',
      'BY' => 'BYR',
      'BZ' => 'BZD',
      'CA' => 'CAD',
      'CC' => 'AUD',
      'CD' => 'CDF',
      'CF' => 'XAF',
      'CG' => 'XAF',
      'CH' => 'CHF',
      'CI' => 'XOF',
      'CK' => 'NZD',
      'CL' => 'CLP',
      'CM' => 'XAF',
      'CN' => 'CNY',
      'CO' => 'COP',
      'CR' => 'CRC',
      'CU' => 'CUP',
      'CV' => 'CVE',
      'CY' => 'EUR',
      'CZ' => 'CZK',
      'DE' => 'EUR',
      'DJ' => 'DJF',
      'DK' => 'DKK',
      'DM' => 'XCD',
      'DO' => 'DOP',
      'DZ' => 'DZD',
      'EC' => 'USD',
      'EE' => 'EEK',
      'EG' => 'EGP',
      'EH' => 'MAD',
      'ER' => 'ERN',
      'ES' => 'EUR',
      'EU' => 'EUR',
      'ET' => 'ETB',
      'FI' => 'EUR',
      'FJ' => 'FJD',
      'FK' => 'FKP',
      'FM' => 'USD',
      'FO' => 'DKK',
      'FR' => 'EUR',
      'GA' => 'XAF',
      'GB' => 'GBP',
      'GD' => 'XCD',
      'GE' => 'GEL',
      'GF' => 'EUR',
      'GH' => 'GHS',
      'GI' => 'GIP',
      'GL' => 'DKK',
      'GM' => 'GMB',
      'GN' => 'GNF',
      'GQ' => 'XAF',
      'GR' => 'EUR',
      'GS' => 'GBP',
      'GT' => 'GTQ',
      'GU' => 'USD',
      'GW' => 'XOF',
      'GY' => 'GYD',
      'HK' => 'HKD',
      'HN' => 'HNL',
      'HR' => 'HRK',
      'HT' => 'HTG',
      'HU' => 'HUF',
      'ID' => 'IDR',
      'IE' => 'EUR',
      'IL' => 'ILS',
      'IN' => 'INR',
      'IO' => 'GBP',
      'IQ' => 'IQD',
      'IR' => 'IRR',
      'IS' => 'ISK',
      'IT' => 'EUR',
      'JM' => 'JMD',
      'JO' => 'JOD',
      'JP' => 'JPY',
      'KE' => 'KES',
      'KG' => 'KGS',
      'KH' => 'KHR',
      'KI' => 'AUD',
      'KM' => 'KMF',
      'KN' => 'XCD',
      'KP' => 'KPW',
      'KR' => 'KRW',
      'KW' => 'KWD',
      'KY' => 'KYD',
      'KZ' => 'KZT',
      'LA' => 'LAK',
      'LB' => 'LBP',
      'LC' => 'XCD',
      'LI' => 'CHF',
      'LK' => 'LKR',
      'LR' => 'LRD',
      'LS' => 'LSL',
      'LT' => 'LTL',
      'LU' => 'EUR',
      'LV' => 'LVL',
      'LY' => 'LYD',
      'MA' => 'MAD',
      'MC' => 'EUR',
      'MD' => 'MDL',
      'MG' => 'MGA',
      'MH' => 'USD',
      'MK' => 'MKD',
      'ML' => 'XOF',
      'MM' => 'MMK',
      'MN' => 'MNT',
      'MO' => 'MOP',
      'MP' => 'USD',
      'MQ' => 'EUR',
      'MR' => 'MRO',
      'MS' => 'XCD',
      'MT' => 'EUR',
      'MU' => 'MUR',
      'MV' => 'MVR',
      'MW' => 'MWK',
      'MX' => 'MXN',
      'MY' => 'MYR',
      'MZ' => 'MZN',
      'NA' => 'NAD',
      'NC' => 'XPF',
      'NE' => 'XOF',
      'NF' => 'AUD',
      'NG' => 'NGN',
      'NI' => 'NIO',
      'NL' => 'EUR',
      'NO' => 'NOK',
      'NP' => 'NPR',
      'NR' => 'AUD',
      'NU' => 'NZD',
      'NZ' => 'NZD',
      'OM' => 'OMR',
      'PA' => 'PAB',
      'PE' => 'PEN',
      'PF' => 'XPF',
      'PG' => 'PGK',
      'PH' => 'PHP',
      'PK' => 'PKR',
      'PL' => 'PLN',
      'PM' => 'EUR',
      'PN' => 'NZD',
      'PR' => 'USD',
      'PT' => 'EUR',
      'PW' => 'USD',
      'PY' => 'PYG',
      'QA' => 'QAR',
      'RE' => 'EUR',
      'RO' => 'RON',
      'RS' => 'RSD',
      'RU' => 'RUB',
      'RW' => 'RWF',
      'SA' => 'SAR',
      'SB' => 'SBD',
      'SC' => 'SCR',
      'SD' => 'SDG',
      'SE' => 'SEK',
      'SG' => 'SGD',
      'SH' => 'SHP',
      'SI' => 'EUR',
      'SK' => 'EUR',
      'SL' => 'SLL',
      'SM' => 'EUR',
      'SN' => 'XOF',
      'SO' => 'SOS',
      'SR' => 'SRD',
      'ST' => 'STD',
      'SV' => 'USD',
      'SY' => 'SYP',
      'SZ' => 'SZL',
      'TC' => 'USD',
      'TD' => 'XAF',
      'TF' => 'EUR',
      'TG' => 'XOF',
      'TH' => 'THB',
      'TJ' => 'TJS',
      'TL' => 'USD',
      'TM' => 'TMM',
      'TN' => 'TND',
      'TO' => 'TOP',
      'TR' => 'TRY',
      'TT' => 'TTD',
      'TV' => 'AUD',
      'TW' => 'TWD',
      'TZ' => 'TZS',
      'UA' => 'UAH',
      'UG' => 'UGX',
      'UM' => 'USD',
      'US' => 'USD',
      'UY' => 'UYU',
      'UZ' => 'UZS',
      'VA' => 'EUR',
      'VC' => 'XCD',
      'VE' => 'VEF',
      'VG' => 'USD',
      'VI' => 'USD',
      'VN' => 'VND',
      'VU' => 'VUV',
      'WF' => 'XPF',
      'WS' => 'WST',
      'YE' => 'YER',
      'YT' => 'EUR',
      'ZA' => 'ZAR',
      'ZM' => 'ZMK',
      'ZW' => 'ZWD'
    }
  end

  def self.currency_for_country( country_iso )
    res = Currency.currencies_for_countries[country_iso]
    if( res.nil? )
      res = Currency.default_currency
    end
    res
  end
  
  def self.currency_list
    Currency.currency_hash.keys.sort
  end

  def self.currency_lookup( currency_iso, column, default = "" )
    res = Currency.currency_hash[currency_iso][column]
    if( res.nil? )
      res = default
    end
    res
  end
  
  def self.currency_symbol(currency_iso)
    self.currency_lookup(currency_iso, :symbol)
  end
  
  def self.currency_name(currency_iso)
    self.currency_lookup(currency_iso, :name)
  end
  
  def self.decimals( currency_iso = 'USD' )
    self.currency_lookup(currency_iso, :decimals, 2) # should be grabbing that 2 from USD defn in array
  end

  def self.currency_url(currency_iso)
    self.currency_lookup(currency_iso, :url)
  end

  def self.round(amt)  
    amt.round(self.decimals)
  end
  
  def self.default_currency
    'USD' # for now, our #1 most popular currency in the app
  end
  
end
